id: P010509
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17487
  title: གསུང་འབུམ། རོང་ཟོམ་ཆོས་ཀྱི་བཟང་པོ།
  author: ''
  volumes:
    d1c0a2411d954533b4be6717ec359601:
      image_group_id: I4PD909
      title: ''
      volume_number: 1
      total_pages: 834
      base_file: v001.txt
    7cae8081b74b4cbfbe69d229190857d6:
      image_group_id: I4PD910
      title: ''
      volume_number: 2
      total_pages: 788
      base_file: v002.txt
    fb8c681fce6a4eb4a5556a6b455e40fe:
      image_group_id: I4PD911
      title: ''
      volume_number: 3
      total_pages: 822
      base_file: v003.txt
