id: IF04A1014
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:25:22+00:00'
last_modified: '2022-06-08T14:07:13.779976+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17487
  title: གསུང་འབུམ། རོང་ཟོམ་ཆོས་ཀྱི་བཟང་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DC41:
      image_group_id: I4PD909
      title: ''
      total_pages: 834
      order: 1
      base_file: DC41.txt
    F300:
      image_group_id: I4PD910
      title: ''
      total_pages: 788
      order: 2
      base_file: F300.txt
    0FFA:
      image_group_id: I4PD911
      title: ''
      total_pages: 822
      order: 3
      base_file: 0FFA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
