id: IF04A1014
legacy_id: P010509
ocr_import_info:
  bdrc_scan_id: W2PD17487
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T13:19:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:18:24.026878+00:00'
last_modified: 2022-09-03 18:19:19.490030
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD17487
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD17487
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རོང་ཟོམ་ཆོས་ཀྱི་བཟང་པོ།
  author: རོང་ཟོམ་པཎྜི་ཏ།
statistics:
  ocr_word_mean_confidence_index: 0.6029124996595926
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I4PD910:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD910
      total_pages: 788
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD910.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6143060230863389
    legacy_id: v002
  I4PD911:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD911
      total_pages: 822
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD911.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6144084266338078
    legacy_id: v003
  I4PD909:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD909
      total_pages: 834
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD909.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5769385609263987
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
